# Generated by Django 4.1.1 on 2022-09-17 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0002_booking_bookingdatetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentinroom",
            options={
                "verbose_name": "Оборудование в аудитории",
                "verbose_name_plural": "Оборудование в аудитории",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Аудитории", "verbose_name_plural": "Аудитории"},
        ),
        migrations.RemoveField(
            model_name="room",
            name="photo",
        ),
        migrations.AlterField(
            model_name="booking",
            name="comment",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Ваш комментарий(только в случае отказа)",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="contact_info",
            field=models.TextField(verbose_name="Контактная информация"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="description",
            field=models.TextField(verbose_name="Цель бронирования"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="equipment",
            field=models.TextField(verbose_name="Забронированное оборудование"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.room",
                verbose_name="Аудитория",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[(0, "В обработке"), (1, "Отклонено"), (2, "Одобрено")],
                default=0,
                verbose_name="Статус заявки",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.TextField(verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="equipmentinroom",
            name="count",
            field=models.PositiveIntegerField(verbose_name="Кол-во оборудования"),
        ),
        migrations.AlterField(
            model_name="equipmentinroom",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentinroom",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.room",
                verbose_name="Аудитория",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="address",
            field=models.TextField(verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="room",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(verbose_name="Вместимость"),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="room",
            name="equipment",
            field=models.ManyToManyField(
                through="booking.EquipmentInRoom",
                to="booking.equipment",
                verbose_name="Оборудование в аудитории",
            ),
        ),
        migrations.CreateModel(
            name="RoomPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="media/images/")),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.room",
                        verbose_name="Аудитория",
                    ),
                ),
            ],
        ),
    ]
