# Generated by Django 4.1.1 on 2022-09-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_options_alter_equipment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomphoto",
            options={"verbose_name": "Фотография", "verbose_name_plural": "Фотографии"},
        ),
        migrations.AlterField(
            model_name="roomphoto",
            name="photo",
            field=models.ImageField(upload_to="images/", verbose_name="Фотография"),
        ),
        migrations.AlterField(
            model_name="roomphoto",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_photo",
                to="booking.room",
                verbose_name="Аудитория",
            ),
        ),
    ]
