# Generated by Django 3.2.7 on 2022-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_roomphoto_options_alter_roomphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdatetime',
            options={'verbose_name': 'Даты и время брони', 'verbose_name_plural': 'Даты и время брони'},
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='end_time',
            field=models.TimeField(verbose_name='Время конца брони'),
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала брони'),
        ),
    ]
