# Generated by Django 3.2.7 on 2022-09-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220920_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='personal_status',
            field=models.IntegerField(choices=[(0, 'Студент'), (1, 'Сотрудник')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='booking',
            name='position',
            field=models.TextField(blank=True, default='', help_text='Должность или группа', verbose_name='Должность/Группа'),
        ),
    ]
