# Generated by Django 3.2.7 on 2022-09-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20220920_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin_contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Контактная информация администратора'),
        ),
    ]
