# Generated by Django 3.2.7 on 2022-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_carousel_carouselphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.AlterModelOptions(
            name='carouselphoto',
            options={'verbose_name': 'Фотографии в карусели', 'verbose_name_plural': 'Фотографии в карусели'},
        ),
        migrations.AddField(
            model_name='carouselphoto',
            name='event',
            field=models.TextField(default='test', verbose_name='Название мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carouselphoto',
            name='address',
            field=models.CharField(max_length=128, verbose_name='В какой аудитории сделана фотография'),
        ),
        migrations.AlterField(
            model_name='carouselphoto',
            name='photo',
            field=models.ImageField(upload_to='carousel_images/', verbose_name='Фотография'),
        ),
    ]
