# Generated by Django 3.2.7 on 2022-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20220925_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.TextField(default='test', verbose_name='Заголовок правил'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='spec_text',
            field=models.TextField(verbose_name='Правила'),
        ),
    ]
