# Generated by Django 3.2.7 on 2022-09-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_staticdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.TextField(default='test', verbose_name='Название мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
