# Generated by Django 3.2.7 on 2022-09-28 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0016_auto_20220927_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pseudo_admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Псевдо администраторы'),
        ),
    ]
