# Generated by Django 3.2.7 on 2022-09-29 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0017_room_pseudo_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Ваш комментарий'),
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца бронирования'),
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала бронирования'),
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время конца брони'),
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала брони'),
        ),
        migrations.AlterField(
            model_name='room',
            name='pseudo_admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Доп. администраторы'),
        ),
    ]
