# Generated by Django 3.2.7 on 2022-09-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20220929_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Общие настройки сайта', 'verbose_name_plural': 'Общие настройки сайта'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='pseudo_text_booking',
            field=models.TextField(default='test', verbose_name='Описание заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='pseudo_text_equipment',
            field=models.TextField(default='test', verbose_name='Описание оборудования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='date_end',
            field=models.DateField(default='2024-09-21', verbose_name='Дата конца бронирования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdatetime',
            name='date_start',
            field=models.DateField(default='2024-09-21', verbose_name='Дата начала бронирования'),
            preserve_default=False,
        ),
    ]
