# Generated by Django 3.2.7 on 2022-10-12 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0019_auto_20220929_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pseudo_admins',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Доп. администраторы'),
        ),
    ]
