# Generated by Django 3.2.7 on 2022-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_room_pseudo_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Забронированное оборудование'),
        ),
    ]
