"""add room and equip tables

Revision ID: 1d120010ee53
Revises: 69c1367984e1
Create Date: 2022-08-29 16:41:07.650157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d120010ee53'
down_revision = '69c1367984e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('admin_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_equipment_association',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('room_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('equipment_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_equipment_association')
    op.drop_table('room')
    op.drop_table('equipment')
    # ### end Alembic commands ###
