"""add booking model

Revision ID: 418655a38f24
Revises: 1d120010ee53
Create Date: 2022-08-30 19:52:06.961111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '418655a38f24'
down_revision = '1d120010ee53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('contact_info', sa.String(length=250), nullable=False),
    sa.Column('room_id', postgresql.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('rejected', 'accepted', 'in_process', name='bookingstatusenum'), nullable=True),
    sa.Column('user_status', sa.Enum('student', 'staff', name='statusenum'), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_date_time',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('booking_id', postgresql.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('room', 'photo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('room', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('room', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('room', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_equipment_association', 'room_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('room_equipment_association', 'equipment_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('room_equipment_association', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user', 'position')
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('room_equipment_association', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_equipment_association', 'equipment_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('room_equipment_association', 'room_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('room', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('room', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('room', 'photo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('booking_date_time')
    op.drop_table('booking')
    # ### end Alembic commands ###
