"""add on booking model

Revision ID: fd39b830974a
Revises: 418655a38f24
Create Date: 2022-08-30 20:26:07.038436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd39b830974a'
down_revision = '418655a38f24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_equipment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_equipment')
    # ### end Alembic commands ###
