# Generated by Django 3.2.7 on 2022-09-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220920_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_mame',
            new_name='full_name',
        ),
    ]
